# Generated by Django 3.2.8 on 2021-11-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ic_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='No. Kad Pengenalan')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('phone_no', models.IntegerField(verbose_name='No. Telefon')),
                ('address1', models.CharField(max_length=100, verbose_name='Alamat 1')),
                ('address2', models.CharField(max_length=100, verbose_name='Alamat 2')),
                ('city', models.CharField(max_length=20, verbose_name='Bandar')),
                ('mukim', models.CharField(max_length=20, verbose_name='Mukim')),
                ('parlimen', models.CharField(max_length=20, verbose_name='Parlimen')),
                ('state', models.CharField(max_length=20, verbose_name='Negeri')),
                ('poskod', models.IntegerField(verbose_name='Poskod')),
            ],
        ),
    ]
