# Generated by Django 3.2.8 on 2021-11-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matric_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Matric Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
    ]
